apiVersion: v1
items:
- apiVersion: neuvector.com/v1
  kind: NvSecurityRule
  metadata:
    name: nv.currencyservice.online-boutique
    namespace: online-boutique
  spec:
    dlp:
      settings: []
      status: false
    egress: []
    file: []
    ingress:
    - action: allow
      applications:
      - HTTP
      name: nv.currencyservice.online-boutique-ingress-0
      ports: any
      priority: 0
      selector:
        comment: ""
        name: Workload:ingress
        original_name: ""
    - action: allow
      applications:
      - any
      name: nv.currencyservice.online-boutique-ingress-1
      ports: tcp/7000
      priority: 0
      selector:
        comment: ""
        name: Workload:ingress
        original_name: ""
    - action: allow
      applications:
      - HTTP
      name: nv.currencyservice.online-boutique-ingress-2
      ports: any
      priority: 0
      selector:
        comment: ""
        criteria:
        - key: service
          op: =
          value: frontend.online-boutique
        - key: domain
          op: =
          value: online-boutique
        name: nv.frontend.online-boutique
        original_name: ""
    - action: allow
      applications:
      - HTTP
      name: nv.currencyservice.online-boutique-ingress-3
      ports: any
      priority: 0
      selector:
        comment: ""
        criteria:
        - key: service
          op: =
          value: checkoutservice.online-boutique
        - key: domain
          op: =
          value: online-boutique
        name: nv.checkoutservice.online-boutique
        original_name: ""
    - action: allow
      applications:
      - any
      name: nv.currencyservice.online-boutique-ingress-4
      ports: tcp/7000
      priority: 0
      selector:
        comment: ""
        criteria:
        - key: service
          op: =
          value: frontend.online-boutique
        - key: domain
          op: =
          value: online-boutique
        name: nv.frontend.online-boutique
        original_name: ""
    process:
    - action: allow
      allow_update: false
      name: node
      path: /usr/local/bin/node
    - action: allow
      allow_update: false
      name: pause
      path: /pause
    process_profile:
      baseline: basic
    target:
      policymode: Protect
      selector:
        comment: ""
        criteria:
        - key: service
          op: =
          value: currencyservice.online-boutique
        - key: domain
          op: =
          value: online-boutique
        name: nv.currencyservice.online-boutique
        original_name: ""
    waf:
      settings: []
      status: true
kind: List
metadata: null
